openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /magic8Ball:
    post:
      tags:
        - magic-8-ball
      operationId: getAnswer
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MagicBall'
  /word:
    get:
      tags:
        - word-of-the-day
      operationId: getWord
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Word'
  /quote:
    get:
      tags:
        - quote-of-the-day
      operationId: getQuote
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    MagicBall:
      type: object
      properties:
        question:
          type: string
        answer:
          type: string
        id:
          type: integer
          format: int32
    Word:
      type: object
      properties:
        word:
          type: string
        definition:
          type: string
        id:
          type: integer
          format: int32
    Quote:
      type: object
      properties:
        author:
          type: string
        quote:
          type: string
        id:
          type: integer
          format: int32
